### ISSUE TITLE
Kesalahan saat menginstall modul

### ISSUE THREAD

**Issue by namzahran01** [irwanx/xyz-wabot#1]
![Screenshot_Termux_20220317-062238](https://user-images.githubusercontent.com/43334234/158707448-a3814006-c1c4-4fd9-8b2d-01322efafe7c.png)
 Udah npm i gini, caranya gmna bang?

**Comment by irwanx** [comment]
Jangan pake termux

**Comment by ilhamn2405** [comment]
> 

bagi modulnya bang

**Comment by namzahran01** [comment]
> Jangan pake termux

Bagi modul botnya bang

**Comment by Ameliascrf** [comment]
Run di heroku aja.. 
Bisa 24jam, tinggal mssukkin scan qr nya/session nya
